export { Home } from './home/Home'
export { About } from './about/About'
export { Contacts } from './contacts/Contacts'
export { Delivery } from './delivery/Delivery'
export { Events } from './events/Events'
